### ISSUE TITLE
feature request: output as azapi

### ISSUE THREAD

**Issue by kewalaka** [lonegunmanb/newres#92]
Loving this, it is really useful - thanks @lonegunmanb 

Is it practical to add a switch that would allow azure resource output to be written for the AzAPI provider instead of AzureRM?

**Comment by lonegunmanb** [comment]
Thanks @kewalaka , I'm glad that you like this tool.

Unfortunately, I don't think I'll support this feature very soon, because `newres` supports [multiple cloud platforms](https://github.com/lonegunmanb/newres?tab=readme-ov-file#supported-providers-and-documentation-limitations).

But we do have a tool [`azapi2azurerm`](https://github.com/Azure/azapi2azurerm), I think maybe we can create a reverse tool based on that.

**Comment by kewalaka** [comment]
yes I saw that, thanks - I had a glance over how it was working and thought that would be your answer, but I thought it doesn't hurt to check 😊.

I've been using azapi2azurerm lately too, also very useful!
